name: 04 - use-Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.17' 
            # this is incoorrect as it runs in root Directory and it fails as there is no package.lock.json
                # - name: Install Dependencies
            #   run: npm ci
            # this is the right way to do it
            - name: Printing Folders
              run: ls
            - name: Where am I?
              run: |
                    pwd
                    ls -la
                    ls -la using-actions/react-app
            - name: Install Dependencies
              run: npm ci
              working-directory: using-actions/react-app